# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  # Exclude generated files
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.mocks.dart'

linter:
  rules:
    - avoid_empty_else
    - avoid_print
    - cancel_subscriptions
    - hash_and_equals
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
    - use_key_in_widget_constructors
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_const_declarations
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
